### ISSUE TITLE
Real-time stabilization

### ISSUE THREAD

**Issue by AlexYiningLiu** [thejarlid/VideoStabilizationPy#1]
Can this code be implemented to work on real-time incoming frames? Thanks.

**Comment by thejarlid** [comment]
This method does not support real-time stabilization. Its functionality requires knowledge of the full real path and then fits a smooth path through it as a constraint problem. Also given its python implementation it is not optimized for extremely heavy workloads. For realtime video stabilization you may want to consider another method. One that comes to mind is using a Kalman Filter that can take a prior state and make an estimate to the next frame/time-step.
